
import { Customer } from './types';

export const CUSTOMERS: Customer[] = [
  { id: 'ST-CUST-001', name: 'Sweet Delights Candy Shop', frequentItemIds: ['SW-CANDY-01', 'SW-CANDY-04', 'SW-CHOC-04'] },
  { id: 'ST-CUST-002', name: 'The Daily Grind Cafe', frequentItemIds: ['SW-CHOC-01', 'SW-CANDY-03'] },
  { id: 'ST-CUST-003', name: 'Confectionery Corner', frequentItemIds: ['SW-CANDY-02', 'SW-CHOC-02', 'SW-CHOC-03'] },
  { id: 'ST-CUST-004', name: 'ChocoHeaven', frequentItemIds: ['SW-CHOC-01', 'SW-CHOC-02', 'SW-CANDY-03'] },
  { id: 'ST-CUST-005', name: "The Baker's Boutique", frequentItemIds: ['SW-CHOC-03', 'SW-CHOC-01'] },
];

export const TRANSLATIONS = {
  en: {
    welcome: "Welcome",
    logout: "Logout",
    recentOrders: "Recent Orders",
    newOrder: "Shop",
    reviewOrder: "Cart",
    adminPanel: "Users",
    inventory: "Inventory",
    searchPlaceholder: "Search products...",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    discountPercentage: "Discount %",
    vat: "VAT",
    tvaIncluded: "TVA included",
    confirmOrder: "Confirm & Place Order",
    back: "Back",
    itemsOrdered: "Items Ordered",
    customerDetails: "Customer Details",
    phone: "Phone",
    address: "Address",
    notes: "Notes",
    status: "Status",
    items: "Items",
    addToOrder: "Add to Order",
    outOfStock: "Out of Stock",
    viewDetails: "View Details",
    login: "Sign In",
    username: "Username",
    password: "Password",
    storeName: "Store Name",
    phoneNumber: "Phone Number",
    phoneError: "Phone number must be exactly 8 digits",
    required: "Required",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    uploadProducts: "Upload Products",
    addUser: "Add User",
    userManagement: "User Management",
    productCatalog: "Product Catalog",
    english: "English",
    arabic: "العربية",
    signInTitle: "Please sign in to continue",
    fillRequired: "Please fill all required fields correctly.",
    orderPlaced: "Order placed successfully!",
    invalidLogin: "Invalid username or password.",
    yourOrderIsEmpty: "Your order is empty",
    addProductsStart: "Add products to get started.",
    backToProducts: "Back to Products",
    orderSummary: "Order Summary",
    placingOrder: "Placing Order...",
    pending: "Pending",
    inProgress: "In Progress",
    done: "Done",
    soldOut: "Sold Out",
    price: "Price",
    category: "Category",
    subCategory: "Sub Category",
    brand: "Brand",
    weight: "Weight",
    packaging: "Packaging",
    unitPerPack: "Unit Per Pack",
    quantity: "Quantity",
    placedBy: "Placed By",
    changePassword: "Change Password",
    existingUsers: "Existing Users",
    addNewSalesman: "Add New User",
    createUser: "Create User",
    uploadInstruction: "Upload a CSV or XLSX file. Images should be URLs or filenames matching the item name.",
    uploadButton: "Upload and Update Products",
    contactInfo: "Contact Us",
    importantNote: "Important Note About Images",
    imageUploadNote: "Images can be URLs or local filenames (eg 'item.jpg'). Local files are assumed to be in the app's image folder.",
    downloadCatalog: "Download Current Catalog",
    poweredBy: "Powered by",
    rightsReserved: "All rights reserved.",
    noProductsFound: "No products found matching your criteria.",
    deleteUserConfirm: "Are you sure you want to delete this account?",
    deleteOrderConfirm: "Are you sure you want to delete this order?",
    userDeleted: "(Deleted User)",
    role: "Role",
    categories: "Categories",
    shopByBrand: "Shop by Brand",
    specialOffers: "Special Offers",
    editItem: "Edit Item",
    updateItem: "Update Item",
    image: "Image",
    vatAmount: "VAT (11%)",
    gallery: "Image Gallery",
    uploadImages: "Upload Images",
    gallerySubtitle: "Manage product images. Images with the same name as products (e.g., 'laziza.jpg') will automatically link.",
    uploading: "Uploading...",
    noImagesInGallery: "No images in gallery yet.",
    editorRestrictionMessage: "Editors are not allowed to place orders.",
    uploadSpecialOffers: "Upload Special Offers",
    uploadSpecialOffersNote: "Upload a file to mark items as 'Special Offers'. Existing items with matching names will be updated.",
  },
  ar: {
    welcome: "مرحباً",
    logout: "خروج",
    recentOrders: "الطلبات الأخيرة",
    newOrder: "المتجر",
    reviewOrder: "السلة",
    adminPanel: "المستخدمين",
    inventory: "المخزون",
    searchPlaceholder: "البحث عن المنتجات...",
    total: "المجموع",
    subtotal: "المجموع الفرعي",
    discount: "خصم",
    discountPercentage: "نسبة الخصم %",
    vat: "الضريبة",
    tvaIncluded: "شامل الضريبة",
    confirmOrder: "تأكيد وإرسال الطلب",
    back: "رجوع",
    itemsOrdered: "المنتجات المطلوبة",
    customerDetails: "تفاصيل العميل",
    phone: "الهاتف",
    address: "العنوان",
    notes: "ملاحظات",
    status: "الحالة",
    items: "المنتجات",
    addToOrder: "أضف للطلب",
    outOfStock: "نفذت الكمية",
    viewDetails: "عرض التفاصيل",
    login: "تسجيل الدخول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    storeName: "اسم المتجر",
    phoneNumber: "رقم الهاتف",
    phoneError: "رقم الهاتف يجب أن يتكون من 8 أرقام",
    required: "مطلوب",
    cancel: "إلغاء",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    uploadProducts: "تحميل المنتجات",
    addUser: "إضافة مستخدم",
    userManagement: "إدارة المستخدمين",
    productCatalog: "كتالوج المنتجات",
    english: "English",
    arabic: "العربية",
    signInTitle: "الرجاء تسجيل الدخول للمتابعة",
    fillRequired: "يرجى ملء جميع الحقول المطلوبة بشكل صحيح.",
    orderPlaced: "تم ارسال الطلب بنجاح!",
    invalidLogin: "اسم المستخدم أو كلمة المرور غير صحيحة.",
    yourOrderIsEmpty: "سلة الطلبات فارغة",
    addProductsStart: "أضف منتجات للبدء.",
    backToProducts: "العودة للمنتجات",
    orderSummary: "ملخص الطلب",
    placingOrder: "جاري إرسال الطلب...",
    pending: "قيد الانتظار",
    inProgress: "قيد التنفيذ",
    done: "مكتمل",
    soldOut: "نفذت الكمية",
    price: "السعر",
    category: "الفئة",
    subCategory: "الفئة الفرعية",
    brand: "العلامة التجارية",
    weight: "الوزن",
    packaging: "التعبئة",
    unitPerPack: "الوحدة لكل عبوة",
    quantity: "الكمية",
    placedBy: "تم الطلب بواسطة",
    changePassword: "تغيير كلمة المرور",
    existingUsers: "المستخدمون الحاليون",
    addNewSalesman: "إضافة مستخدم جديد",
    createUser: "إنشاء مستخدم",
    uploadInstruction: "قم بتحميل ملف CSV أو XLSX. يجب أن تكون الصور روابط أو أسماء ملفات.",
    uploadButton: "تحميل وتحديث المنتجات",
    contactInfo: "اتصل بنا",
    importantNote: "ملاحظة مهمة حول الصور",
    imageUploadNote: "يمكن أن تكون الصور روابط أو أسماء ملفات محلية (مثل 'item.jpg').",
    downloadCatalog: "تحميل الكتالوج الحالي",
    poweredBy: "مدعوم من",
    rightsReserved: "جميع الحقوق محفوظة.",
    noProductsFound: "لا توجد منتجات تطابق معايير البحث.",
    deleteUserConfirm: "هل أنت متأكد أنك تريد حذف هذا الحساب؟",
    deleteOrderConfirm: "هل أنت متأكد أنك تريد حذف هذا الطلب؟",
    userDeleted: "(مستخدم محذوف)",
    role: "الدور",
    categories: "الفئات",
    shopByBrand: "تسوق حسب العلامة التجارية",
    specialOffers: "عروض خاصة",
    editItem: "تعديل المنتج",
    updateItem: "تحديث المنتج",
    image: "الصورة",
    vatAmount: "الضريبة (11%)",
    gallery: "معرض الصور",
    uploadImages: "تحميل الصور",
    gallerySubtitle: "إدارة صور المنتجات. سيتم ربط الصور بنفس اسم المنتجات تلقائيًا (مثل 'laziza.jpg').",
    uploading: "جاري التحميل...",
    noImagesInGallery: "لا توجد صور في المعرض بعد.",
    editorRestrictionMessage: "لا يُسمح للمحررين بتقديم الطلبات.",
    uploadSpecialOffers: "تحميل العروض الخاصة",
    uploadSpecialOffersNote: "قم بتحميل ملف لتحديد العناصر كـ 'عروض خاصة'. سيتم تحديث العناصر الموجودة بنفس الأسماء.",
  }
};
